### ISSUE TITLE
Problem using the model directly via Docker

### ISSUE THREAD

**Issue by lisadratva** [1edv/evolution#1]
Hello,

I am trying to run the model using your instructions via Docker. I succeeded with running the app in the browser via Docker, however I am unable to execute the python commands in the shell to run the model directly. The first line from your python shell instructions (`from app_aux import *`) throws the error `ModuleNotFoundError: No module named 'app_aux'`. I tried importing the `load_model `function from the other modules present, `app.py` and `aux_app.py`, but that also doesn't work. What command should I execute inside the Docker container to correctly load the model?

Thank you for your help!

**Comment by 1edv** [comment]
Hi,

Thank you for the question ! I just pushed an update that fixed this issue (the issue was that the file app_aux.py was missing). Feel free to re-open the issue if you still have questions.
