### ISSUE TITLE
Positional Encodings

### ISSUE THREAD

**Issue by aga-relation** [1edv/evolution#13]
Hi, 

If I am reading your code correctly, you are not using any positional encodings - is that right? Any reasons for it?
Thank you! :)

**Comment by 1edv** [comment]
Hi, 

Thank you for your your question!

That is correct - we aren't using any positional encodings. There wasn't a strong reason for not using positional encodings, just the fact that we had a few convolutional layers before the transformer encoder layer.

Best,
Eeshit
