### ISSUE TITLE
Download 20190325_NBT_MolEvol_seq_data_SCUra_YPD.splitByOrigID.meanEL.min100reads.txt

### ISSUE THREAD

**Issue by ChihHanHuang** [1edv/evolution#6]
Dear Author,

Thank you for the great work!
I would like to ask the location to download 20190325_NBT_MolEvol_seq_data_SCUra_YPD.splitByOrigID.meanEL.min100reads.txt describing in data_processing.ipynb
Thank you very much

Best regards,

Robin

**Comment by 1edv** [comment]
Dear Robin,

Thank you! I have added that file to the same directory as the code now. It can be accessed here : 
https://github.com/1edv/evolution/blob/master/manuscript_code/model/tpu_model/20190325_NBT_MolEvol_seq_data_SCUra_YPD.splitByOrigID.meanEL.min100reads.txt

Best,
Eeshit.

**Comment by ChihHanHuang** [comment]
Thank you very much!
